site_name: 黄花鱼的试验田

nav:
  - Pytorch:
    - Tensor: pytorch/1.tensor.md
    - Datasets: pytorch/2.datasets.md
  - Tools:
    - mkdocs:
      - markdown_extensions: Tools/mkdocs/markdown_extensions.md
  - 课程笔记:
    - 计算理论:
      - "Chapter I":
        - 基本定义: course note/CT/C1/string.md
        - DFA: course note/CT/C1/DFA.md
        - NFA: course note/CT/C1/NFA.md
        - regular language: course note/CT/C1/regular language.md
      - "Chapter II":
        - CFG: course note/CT/C2/CFG.md
        - PDA: course note/CT/C2/PDA.md
        - CFG_next: course note/CT/C2/CFG2.md
  - CG:
    - Unity 3D:
      - Game objects and script: CG/U3D/001.md
      
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      accent: red
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: red
  font:
    text: Roboto
    code: Roboto Mono
  language: zh
  icon:
    logo: material/library


markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets: 
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs"]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
